export type AppStatus = 'native' | 'web' | 'bridge' | 'blocked';
export type Category = 'All' | 'Development' | 'Design' | 'Communication' | 'Productivity' | 'Media' | 'Gaming';

export type WorkApp = {
  id: string;
  name: string;
  monogram: string;
  color: string;
  category: Exclude<Category, 'All'>;
  status: AppStatus;
  note: string;
  plan: string;
  source: string;
};

export const APPS: WorkApp[] = [
  { id: 'photoshop', name: 'Photoshop', monogram: 'Ps', color: '#2163e8', category: 'Design', status: 'blocked', note: 'No supported Linux desktop build', plan: 'Keep a Windows or macOS lane for production work. The built-in Windows VM has no GPU passthrough, so dual boot or a second machine is the honest route.', source: 'https://helpx.adobe.com/photoshop/desktop/get-started/technical-requirements-installation/adobe-photoshop-on-desktop-technical-requirements.html' },
  { id: 'illustrator', name: 'Illustrator', monogram: 'Ai', color: '#e98112', category: 'Design', status: 'blocked', note: 'No supported Linux desktop build', plan: 'Use a separate Windows/macOS environment for production Illustrator work. Inkscape is worth testing, but file fidelity must be validated against your real deliverables.', source: 'https://helpx.adobe.com/illustrator/system-requirements.html' },
  { id: 'figma', name: 'Figma', monogram: 'Fi', color: '#f24e1e', category: 'Design', status: 'web', note: 'Primary workflow is browser-based', plan: 'Install Figma as an Omarchy web app. Test fonts, local font access, and any organization-specific plugins before wiping another OS.', source: 'https://help.figma.com/hc/en-us/articles/5601429983767-Guide-to-the-Figma-desktop-app' },
  { id: 'canva', name: 'Canva', monogram: 'Ca', color: '#00a6a6', category: 'Design', status: 'web', note: 'Works through the browser', plan: 'Use Canva as a Chromium web app. Keep a browser profile dedicated to creative work if you use multiple accounts.', source: 'https://www.canva.com/download/' },
  { id: 'vscode', name: 'VS Code', monogram: '</>', color: '#1782d0', category: 'Development', status: 'native', note: 'Native Linux build', plan: 'Install from Omarchy’s editor menu, then sync settings. Validate remote containers and any proprietary extension before migrating.', source: 'https://code.visualstudio.com/docs/setup/linux' },
  { id: 'cursor', name: 'Cursor', monogram: 'Cu', color: '#242424', category: 'Development', status: 'native', note: 'Available from Omarchy’s editor menu', plan: 'Install from Omarchy’s editor menu. Export any local rules, snippets, and MCP configuration separately from account sync.', source: 'https://omarchy.org/manual/development-tools/' },
  { id: 'jetbrains', name: 'JetBrains IDEs', monogram: 'JB', color: '#d3298f', category: 'Development', status: 'native', note: 'Linux builds are available', plan: 'Install Toolbox or the IDE package you use. Re-test file watchers, Docker integration, and global shortcuts under Wayland.', source: 'https://www.jetbrains.com/toolbox-app/' },
  { id: 'docker', name: 'Docker', monogram: 'Do', color: '#1479e8', category: 'Development', status: 'native', note: 'Included in the Omarchy workflow', plan: 'Use Omarchy’s Docker setup and move projects through Git, not by copying active volumes. Recreate databases from dumps or migrations.', source: 'https://omarchy.org/manual/development-tools/' },
  { id: 'android-studio', name: 'Android Studio', monogram: 'An', color: '#40a76b', category: 'Development', status: 'native', note: 'Official Linux support', plan: 'Install the Linux build and restore SDKs selectively. Confirm hardware acceleration and USB debugging on your actual device.', source: 'https://developer.android.com/studio/install' },
  { id: 'xcode', name: 'Xcode / iOS', monogram: 'X', color: '#168af2', category: 'Development', status: 'bridge', note: 'CI can build; local Simulator still needs macOS', plan: 'Code on Omarchy, build and test in a macOS runner or Xcode Cloud, and keep access to a Mac for Simulator, signing diagnostics, and device debugging.', source: 'https://developer.apple.com/documentation/Xcode/Xcode-Cloud' },
  { id: 'windows-builds', name: 'Windows builds', monogram: 'Win', color: '#1675d1', category: 'Development', status: 'bridge', note: 'Build on a hosted Windows runner', plan: 'Send tagged builds to a Windows GitHub Actions runner and upload signed output as an artifact. Keep a Windows test lane for runtime and installer QA.', source: 'https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job' },
  { id: 'slack', name: 'Slack', monogram: '#', color: '#7c3aed', category: 'Communication', status: 'native', note: 'Linux app and web workflow', plan: 'Use the Linux app or install the web version. Verify screen sharing, audio routing, and notification behavior before committing.', source: 'https://slack.com/downloads/linux' },
  { id: 'discord', name: 'Discord', monogram: 'Di', color: '#5865f2', category: 'Communication', status: 'native', note: 'Linux desktop build', plan: 'Install the Linux app and verify screen sharing under Wayland for your exact use case.', source: 'https://discord.com/download' },
  { id: 'zoom', name: 'Zoom', monogram: 'Zm', color: '#2d8cff', category: 'Communication', status: 'native', note: 'Official Linux client', plan: 'Install the Linux client, then run a test call covering camera, microphone, screen sharing, and virtual backgrounds.', source: 'https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0063458' },
  { id: 'notion', name: 'Notion', monogram: 'N', color: '#171717', category: 'Productivity', status: 'web', note: 'Browser workflow is the safe route', plan: 'Install Notion as a web app. Check offline expectations first—the browser route is strongest when you stay connected.', source: 'https://www.notion.com/help/notion-for-web' },
  { id: 'microsoft-365', name: 'Microsoft 365', monogram: 'M', color: '#e05a26', category: 'Productivity', status: 'bridge', note: 'Web apps or the built-in Windows VM', plan: 'Start with Microsoft 365 on the web. For advanced desktop-only features, use Omarchy’s Windows VM; it is explicitly suited to Office-class apps.', source: 'https://omarchy.org/manual/windows-vm/' },
  { id: 'obsidian', name: 'Obsidian', monogram: 'Ob', color: '#7c4dff', category: 'Productivity', status: 'native', note: 'Included in the Omarchy experience', plan: 'Move the vault through your existing sync method, then review community plugins before enabling all of them on the new system.', source: 'https://omarchy.org/manual/guis/' },
  { id: 'spotify', name: 'Spotify', monogram: 'Sp', color: '#1db954', category: 'Media', status: 'native', note: 'Easy install in Omarchy', plan: 'Install through Omarchy’s service menu. Offline playback is supported by the Linux app.', source: 'https://omarchy.org/manual/commercial-apps-services/' },
  { id: 'obs', name: 'OBS Studio', monogram: 'OBS', color: '#3d3d45', category: 'Media', status: 'native', note: 'Included in Omarchy', plan: 'Import a copy of your scenes, then reselect PipeWire audio sources and verify hardware encoding before a real stream.', source: 'https://omarchy.org/manual/' },
  { id: 'premiere', name: 'Premiere Pro', monogram: 'Pr', color: '#6f49d8', category: 'Media', status: 'blocked', note: 'No supported Linux desktop build', plan: 'Keep Windows/macOS for Premiere projects. Omarchy’s Windows VM has no GPU passthrough and is not intended for video editing.', source: 'https://helpx.adobe.com/premiere-pro/system-requirements.html' },
  { id: 'davinci', name: 'DaVinci Resolve', monogram: 'DR', color: '#cf533d', category: 'Media', status: 'bridge', note: 'Linux exists, but workflow compatibility varies', plan: 'Test a real project before switching. Codecs, GPU drivers, plugins, and Arch packaging can turn an apparently native app into a migration project.', source: 'https://www.blackmagicdesign.com/support/family/davinci-resolve-and-fusion' },
  { id: 'postman', name: 'Postman', monogram: 'Po', color: '#ff6c37', category: 'Development', status: 'native', note: 'Official Linux desktop build', plan: 'Install the Linux build, sign in, and test local/private API access, certificates, proxy rules, and scripts before removing your current workstation.', source: 'https://www.postman.com/downloads/' },
  { id: 'insomnia', name: 'Insomnia', monogram: 'In', color: '#5b4bdb', category: 'Development', status: 'native', note: 'Official Linux packages are available', plan: 'Install the Linux package, import a copy of your projects, and verify environment secrets, plugins, and certificate handling.', source: 'https://insomnia.rest/download' },
  { id: 'dbeaver', name: 'DBeaver', monogram: 'Db', color: '#8a6d4b', category: 'Development', status: 'native', note: 'Verified Linux desktop support', plan: 'Install the Linux build and re-create one non-production connection first. Confirm SSH tunnels, native drivers, credential storage, and exports.', source: 'https://dbeaver.io/download/' },
  { id: 'zed', name: 'Zed', monogram: 'Z', color: '#475569', category: 'Development', status: 'native', note: 'Official Linux installer supports Arch', plan: 'Install the official Linux build, import only the settings you need, and test language servers, extensions, SSH projects, and GPU rendering.', source: 'https://zed.dev/docs/installation' },
  { id: 'sublime', name: 'Sublime Text', monogram: 'Su', color: '#ff9800', category: 'Development', status: 'native', note: 'Official Linux packages', plan: 'Install the official package, restore your license and packages, then verify build systems and project-specific tooling.', source: 'https://www.sublimetext.com/docs/linux_repositories.html' },
  { id: 'neovim', name: 'Neovim', monogram: 'Nv', color: '#57a143', category: 'Development', status: 'native', note: 'Native on Arch Linux', plan: 'Install from the Arch repository, restore a clean config, then run health checks and validate LSP, clipboard, fonts, and terminal integration.', source: 'https://neovim.io/doc/user/install.html' },
  { id: 'godot', name: 'Godot Engine', monogram: 'Go', color: '#478cbf', category: 'Development', status: 'native', note: 'Official self-contained Linux editor', plan: 'Open a copy of a real project, install matching export templates, and test GPU rendering, plugins, C# tooling, and target exports.', source: 'https://godotengine.org/download/linux/' },
  { id: 'blender', name: 'Blender', monogram: 'Bl', color: '#e87d0d', category: 'Design', status: 'native', note: 'Official Linux release', plan: 'Open a copy of a production scene and test GPU compute, color management, add-ons, fonts, render output, and asset paths.', source: 'https://www.blender.org/download/' },
  { id: 'krita', name: 'Krita', monogram: 'Kr', color: '#3babff', category: 'Design', status: 'native', note: 'Official Linux AppImage', plan: 'Test a real layered file, tablet pressure, color profiles, fonts, brushes, and export settings before migrating your art workflow.', source: 'https://krita.org/en/download/' },
  { id: 'gimp', name: 'GIMP', monogram: 'Gi', color: '#5c5543', category: 'Design', status: 'native', note: 'First-class Linux application', plan: 'Test the exact file formats, plugins, color profiles, fonts, and automation scripts your work depends on.', source: 'https://www.gimp.org/downloads/' },
  { id: 'inkscape', name: 'Inkscape', monogram: 'Ik', color: '#334155', category: 'Design', status: 'native', note: 'Official Linux support', plan: 'Open representative SVG, PDF, and imported Illustrator files. Verify fonts, linked assets, color output, and round-trip fidelity.', source: 'https://inkscape.org/release/' },
  { id: 'affinity', name: 'Affinity Suite', monogram: 'Af', color: '#7c3aed', category: 'Design', status: 'blocked', note: 'No supported Linux desktop build', plan: 'Keep Windows or macOS for Affinity production work. Treat Wine experiments as non-production until your real files, plugins, and exports pass.', source: 'https://affinity.serif.com/en-us/' },
  { id: 'sketch', name: 'Sketch', monogram: 'Sk', color: '#f7b500', category: 'Design', status: 'blocked', note: 'The editor requires macOS', plan: 'Keep access to a Mac for authoring. Browser handoff and inspect tools can help collaborators, but they do not replace the native editor.', source: 'https://www.sketch.com/docs/getting-started/system-requirements/' },
  { id: 'lightroom', name: 'Lightroom', monogram: 'Lr', color: '#31a8ff', category: 'Design', status: 'bridge', note: 'Web workflow exists; desktop does not support Linux', plan: 'Test Lightroom on the web for your actual library, imports, exports, presets, and storage limits. Keep a supported OS if desktop features are required.', source: 'https://lightroom.adobe.com/' },
  { id: 'teams', name: 'Microsoft Teams', monogram: 'Tm', color: '#6264a7', category: 'Communication', status: 'web', note: 'Use the browser/PWA route on Linux', plan: 'Install Teams as a Chromium web app and run a real meeting test covering camera, microphone, notifications, screen share, and your tenant policies.', source: 'https://learn.microsoft.com/en-us/microsoftteams/new-teams-web' },
  { id: 'google-meet', name: 'Google Meet', monogram: 'Me', color: '#00ac47', category: 'Communication', status: 'web', note: 'Browser-first workflow', plan: 'Run a meeting in your production browser profile and verify screen sharing, multiple displays, camera effects, audio routing, and recording permissions.', source: 'https://support.google.com/meet/answer/7317473' },
  { id: 'telegram', name: 'Telegram', monogram: 'Tg', color: '#229ed9', category: 'Communication', status: 'native', note: 'Official Linux desktop build', plan: 'Install Telegram Desktop, restore the account, then verify downloads, notification rules, calls, and local storage expectations.', source: 'https://desktop.telegram.org/' },
  { id: 'signal', name: 'Signal', monogram: 'Si', color: '#3a76f0', category: 'Communication', status: 'native', note: 'Official Linux desktop options', plan: 'Install the official AppImage or package, link the device, and verify calls, notifications, attachments, and desktop history behavior.', source: 'https://signal.org/download/' },
  { id: 'whatsapp', name: 'WhatsApp', monogram: 'Wa', color: '#25d366', category: 'Communication', status: 'web', note: 'Use WhatsApp Web on Linux', plan: 'Install WhatsApp Web as a web app and test calls, notifications, file downloads, and multi-device behavior before relying on it.', source: 'https://web.whatsapp.com/' },
  { id: 'google-workspace', name: 'Google Workspace', monogram: 'G', color: '#4285f4', category: 'Productivity', status: 'web', note: 'Docs, Sheets, Slides, and Gmail are browser-based', plan: 'Use a dedicated browser profile and test offline mode, Drive uploads, large files, printing, fonts, macros, and organization extensions.', source: 'https://workspace.google.com/' },
  { id: 'linear', name: 'Linear', monogram: 'Li', color: '#5e6ad2', category: 'Productivity', status: 'web', note: 'Full browser workflow', plan: 'Install Linear as a web app and verify shortcuts, notifications, file uploads, SSO, and integrations in your workspace.', source: 'https://linear.app/' },
  { id: 'jira', name: 'Jira', monogram: 'Ji', color: '#1868db', category: 'Productivity', status: 'web', note: 'Browser-first workflow', plan: 'Test your real Jira site in Chromium, including SSO, marketplace apps, rich editor behavior, attachments, and notifications.', source: 'https://www.atlassian.com/software/jira' },
  { id: 'trello', name: 'Trello', monogram: 'Tr', color: '#0c66e4', category: 'Productivity', status: 'web', note: 'Works in the browser', plan: 'Install Trello as a web app and verify boards, Power-Ups, drag-and-drop, uploads, notifications, and offline expectations.', source: 'https://trello.com/' },
  { id: 'asana', name: 'Asana', monogram: 'As', color: '#f06a6a', category: 'Productivity', status: 'web', note: 'Browser workflow is the Linux route', plan: 'Test your production workspace, SSO, forms, uploads, notifications, and any browser-extension integrations.', source: 'https://app.asana.com/' },
  { id: 'airtable', name: 'Airtable', monogram: 'At', color: '#f82b60', category: 'Productivity', status: 'web', note: 'Full browser application', plan: 'Test large bases, extensions, automations, CSV import/export, SSO, and browser memory use with your real workspace.', source: 'https://airtable.com/' },
  { id: 'miro', name: 'Miro', monogram: 'Mi', color: '#ffd02f', category: 'Productivity', status: 'web', note: 'Browser route works on Linux', plan: 'Open a heavy production board and test video calls, screen share, stylus input, uploads, fonts, and organization controls.', source: 'https://miro.com/app/' },
  { id: 'dropbox', name: 'Dropbox', monogram: 'Dx', color: '#0061ff', category: 'Productivity', status: 'native', note: 'Official Linux desktop client', plan: 'Install the Linux client and test selective sync, large files, shared folders, symlinks, filesystem locations, and team policies.', source: 'https://www.dropbox.com/install-linux' },
  { id: 'onepassword', name: '1Password', monogram: '1P', color: '#3b82f6', category: 'Productivity', status: 'native', note: 'Official Linux app', plan: 'Install the official package and test browser integration, SSH agent, biometric expectations, CLI access, and enterprise policies.', source: 'https://support.1password.com/install-linux/' },
  { id: 'bitwarden', name: 'Bitwarden', monogram: 'Bw', color: '#175ddc', category: 'Productivity', status: 'native', note: 'Official Linux desktop app', plan: 'Install the desktop app and browser extension, then test unlock, passkeys, attachments, organizations, and your self-hosted endpoint if used.', source: 'https://bitwarden.com/download/' },
  { id: 'todoist', name: 'Todoist', monogram: 'Td', color: '#e44332', category: 'Productivity', status: 'native', note: 'Official Linux package', plan: 'Install the Linux app or web app and verify global quick-add expectations, notifications, offline state, and calendar integrations.', source: 'https://todoist.com/downloads' },
  { id: 'vlc', name: 'VLC', monogram: 'VLC', color: '#f97316', category: 'Media', status: 'native', note: 'Native cross-platform media player', plan: 'Install from the Arch repository and test uncommon codecs, subtitles, network streams, hardware decoding, and audio passthrough.', source: 'https://www.videolan.org/vlc/' },
  { id: 'audacity', name: 'Audacity', monogram: 'Au', color: '#2563eb', category: 'Media', status: 'native', note: 'Official Linux AppImage', plan: 'Open a copy of a real project and verify audio devices, PipeWire routing, plugins, FFmpeg imports, recording latency, and exports.', source: 'https://www.audacityteam.org/download/' },
  { id: 'kdenlive', name: 'Kdenlive', monogram: 'Kd', color: '#527eb2', category: 'Media', status: 'native', note: 'Official Linux AppImage and Flatpak', plan: 'Test a real timeline with your codecs, proxies, GPU effects, plugins, audio routing, subtitles, and final delivery export.', source: 'https://kdenlive.org/en/download/' },
  { id: 'handbrake', name: 'HandBrake', monogram: 'Hb', color: '#59a52c', category: 'Media', status: 'native', note: 'Linux builds are supported', plan: 'Encode representative media and compare hardware acceleration, subtitles, chapters, presets, output quality, and throughput.', source: 'https://handbrake.fr/downloads.php' },
  { id: 'after-effects', name: 'After Effects', monogram: 'Ae', color: '#8b5cf6', category: 'Media', status: 'blocked', note: 'No supported Linux desktop build', plan: 'Keep Windows or macOS for After Effects. A VM without GPU passthrough is not a production motion-graphics workstation.', source: 'https://helpx.adobe.com/after-effects/system-requirements.html' },
  { id: 'final-cut', name: 'Final Cut Pro', monogram: 'Fc', color: '#334155', category: 'Media', status: 'blocked', note: 'Requires macOS', plan: 'Keep a Mac lane for editing, libraries, plugins, Motion templates, and delivery. Exporting XML is a migration experiment, not automatic compatibility.', source: 'https://www.apple.com/final-cut-pro/specs/' },
  { id: 'ableton', name: 'Ableton Live', monogram: 'Ab', color: '#525252', category: 'Media', status: 'blocked', note: 'Supported only on Windows and macOS', plan: 'Keep a supported OS for sessions, plugins, audio drivers, controllers, licensing, and live performance. Do not make Wine your only stage rig.', source: 'https://help.ableton.com/hc/en-us/articles/115001663530-Live-Minimum-System-Requirements' },
  { id: 'fl-studio', name: 'FL Studio', monogram: 'FL', color: '#f97316', category: 'Media', status: 'blocked', note: 'No supported Linux edition', plan: 'Keep Windows or macOS for production projects, VSTs, audio drivers, licensing, and controller workflows. Treat Wine as a test lane only.', source: 'https://www.image-line.com/fl-studio-download/' },
  { id: 'steam', name: 'Steam', monogram: 'St', color: '#1b6fa8', category: 'Gaming', status: 'native', note: 'Native Linux client with Proton', plan: 'Install Steam, enable Proton selectively, and test the exact games, anti-cheat, controllers, overlays, HDR, and save sync you depend on.', source: 'https://store.steampowered.com/about/' },
  { id: 'lutris', name: 'Lutris', monogram: 'Lu', color: '#ff9d2e', category: 'Gaming', status: 'native', note: 'Linux-native game manager', plan: 'Install one game at a time and record the runner, prefix, dependencies, controller behavior, and save location that actually work.', source: 'https://lutris.net/' },
  { id: 'heroic', name: 'Heroic Launcher', monogram: 'He', color: '#7c3aed', category: 'Gaming', status: 'native', note: 'Linux client for Epic, GOG, and Amazon', plan: 'Install the official Linux build and test the exact game, Wine/Proton runner, cloud saves, DLC, controller, and overlay behavior.', source: 'https://heroicgameslauncher.com/' },
  { id: 'epic', name: 'Epic Games Launcher', monogram: 'Eg', color: '#313131', category: 'Gaming', status: 'bridge', note: 'Use Heroic or Lutris; no native Epic client', plan: 'Use Heroic for supported Epic titles or Lutris for the official launcher. Check each game for anti-cheat, DRM, cloud saves, and launcher dependencies.', source: 'https://heroicgameslauncher.com/' },
  { id: 'battlenet', name: 'Battle.net', monogram: 'Bn', color: '#148eff', category: 'Gaming', status: 'bridge', note: 'Runs through a compatibility layer', plan: 'Install through Lutris and test every required game, update cycle, anti-cheat, voice chat, controller, and GPU path before switching.', source: 'https://lutris.net/about' },
  { id: 'minecraft-java', name: 'Minecraft Java', monogram: 'Mc', color: '#5c913b', category: 'Gaming', status: 'bridge', note: 'Java runs natively; launcher packaging varies', plan: 'Test the launcher you will actually use, Microsoft sign-in, Java version, modpack, shaders, controller setup, and multiplayer servers.', source: 'https://www.minecraft.net/en-us/download' },
];

export const CATEGORIES: Category[] = ['All', 'Development', 'Design', 'Communication', 'Productivity', 'Media', 'Gaming'];

export const STATUS_META: Record<AppStatus, { label: string; shortLabel: string; action: string; weight: number }> = {
  native: { label: 'Native path', shortLabel: 'Native', action: 'MOVE', weight: 100 },
  web: { label: 'Web-ready', shortLabel: 'Web', action: 'WRAP', weight: 85 },
  bridge: { label: 'Needs a bridge', shortLabel: 'Bridge', action: 'BRIDGE', weight: 55 },
  blocked: { label: 'Hard blocker', shortLabel: 'Blocked', action: 'KEEP', weight: 0 },
};
